###
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "supra",
  "price": 5100,
  "year": 1952,
  "mileage": 30000,
  "lng": 101.8613,
  "lat": 3.9523
}

###
PATCH  http://localhost:3000/reports/10
Content-Type: application/json

{
  "approved": true
}

###
GET http://localhost:3000/reports?year=1950&make=toyota&model=supra&mileage=40000&lng=102&lat=2