###
POST http://localhost:3000/reports
Content-Type: application/json

{
  "make": "toyota",
  "model": "corolla",
  "price": 0,
  "year": 1940,
  "mileage": 0,
  "lng": 0,
  "lat": 0
}

###
PATCH  http://localhost:3000/reports/6
Content-Type: application/json

{
  "approved": false
}

###
GET http://localhost:3000/reports?year=1940&make=toyota&model=corolla&mileage=0&lng=0&lat=0