POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test@asd.com",
  "password": "password"
}
 
###
GET http://localhost:3000/auth/333

###
GET http://localhost:3000/auth?email=test@asd.com

###
DELETE http://localhost:3000/auth/1

###
PATCH http://localhost:3000/auth/133
Content-Type: application/json

{
  "password": "aaabbb"
}

###
POST http://localhost:3000/auth/signin

{
  "email": "test@asd.com",
  "password": "password"
}